language: node_js
os:
  - linux
  - osx
branches:
  only:
  - prebuild
node_js:
  - "10"
install:
  - npm install
  - npm run tsc
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -qq install g++-4.8 g++-multilib; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8 ; fi
script:
  - node node_modules/prebuild/bin.js --all -u $GITHUB_RELEASE_TOKEN
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then node node_modules/prebuild/bin.js --all -a ia32 -u $GITHUB_RELEASE_TOKEN ; fi
